In [1]:
import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta

In [2]:
data = yf.download("AAPL", start=datetime.now() - timedelta(days=365), end=datetime.now())

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

In [3]:
data.tail()

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-05-20  206.860001  208.470001  205.029999  207.669998  42496600
2025-05-21  202.089996  207.039993  200.710007  205.169998  59211800
2025-05-22  201.360001  202.750000  199.699997  200.710007  46742400
2025-05-23  195.270004  197.699997  193.460007  193.669998  78314800
2025-05-27  200.090103  200.649994  197.429993  198.300003  29449698

In [4]:
# Get s&p 500 company symbols
s_n_p_stocks = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]['Symbol'].tolist()

In [5]:
companies = [ stock for stock in s_n_p_stocks if '.B' not in stock]
companies

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BK',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BLDR',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'COIN',
 'CL',
 'CMCSA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [6]:
# down load the data for all s&p 500 companies
start_date = datetime.now() - timedelta(days=365*5)
end_date = datetime.now()
historical_data = yf.download(companies,start=start_date, end=end_date)
historical_data.head()

[*********************100%***********************]  501 of 501 completed

1 Failed download:
['DAY']: Timeout('Failed to perform, curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')

Price      Adj Close      Close                                        \
Ticker           DAY          A       AAPL       ABBV ABNB        ABT
Date
2020-05-28       NaN  83.811623  77.340240  73.355904  NaN  84.290581
2020-05-29       NaN  85.213470  77.264908  75.506966  NaN  86.871468
2020-06-01       NaN  86.924706  78.215111  73.901825  NaN  85.123421
2020-06-02       NaN  87.292099  78.577202  74.178825  NaN  84.766487
2020-06-03       NaN  87.485435  79.009781  74.056625  NaN  83.649948

Price                                                      ...  Volume  \
Ticker           ACGL         ACN        ADBE         ADI  ...     WTW
Date                                                       ...
2020-05-28  27.614094  187.229416  379.829987  101.929108  ...  560900
2020-05-29  26.834356  187.183014  386.600006  103.757133  ...  915800
2020-06-01  27.671148  188.817017  389.679993  103.600967  ...  548300
2020-06-02  28.888296  191.045166  390.440002  107.293785  ...  834000
2020-06-03  30.761566  192.437729  389.920013  111.721512  ...  698100

Price                                                                         \
Ticker            WY     WYNN      XEL       XOM      XYL       YUM      ZBH
Date
2020-05-28   5640000  5005800  2640400  19698000  1306200   4065700   987770
2020-05-29  11299800  5123600  3972300  25874700  1624600  14610100  1386174
2020-06-01   5384400  3707700  1897800  19031000   824200   2014100   630360
2020-06-02   4758000  5619900  3477700  22319000  1187700   2483900  1062857
2020-06-03   4155200  8273900  2591400  23418000   989400   2667100  1423872

Price
Ticker        ZBRA      ZTS
Date
2020-05-28  334000  2367800
2020-05-29  490700  2814500
2020-06-01  294100  1413000
2020-06-02  266000  1649100
2020-06-03  334400  1459500

[5 rows x 2506 columns]

In [7]:
#not losing original data while doing operations
historical_prices = historical_data

# the level 0 columns list

pd.unique(historical_prices.columns.get_level_values(0).to_list())

/tmp/ipykernel_1651535/3422064446.py:6: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  pd.unique(historical_prices.columns.get_level_values(0).to_list())

array(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'],
      dtype=object)

In [8]:
# Only closing prices needed
historical_prices = historical_prices.loc[:,historical_prices.columns.get_level_values(0) == 'Close']
historical_prices.columns = historical_prices.columns.droplevel(0)
historical_prices.head()

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-05-28,83.811623,77.340240,73.355904,NaN,84.290581,27.614094,187.229416,379.829987,101.929108,33.981678,...,192.207382,17.877068,81.222801,54.852829,35.888233,64.481750,83.189491,119.549049,257.420013,132.591156
2020-05-29,85.213470,77.264908,75.506966,NaN,86.871468,26.834356,187.183014,386.600006,103.757133,34.251793,...,189.637192,16.834793,81.300880,55.726921,36.230854,62.759945,82.163963,118.007851,261.320007,133.820053
2020-06-01,86.924706,78.215111,73.901825,NaN,85.123421,27.671148,188.817017,389.679993,103.600967,33.885838,...,189.225922,17.551878,84.415085,56.343922,36.876278,62.438297,82.887337,119.446304,264.970001,132.812027
2020-06-02,87.292099,78.577202,74.178825,NaN,84.766487,28.888296,191.045166,390.440002,107.293785,34.565472,...,187.982849,18.093855,82.101402,56.618134,37.696991,64.235771,84.434814,120.006721,264.089996,135.826538
2020-06-03,87.485435,79.009781,74.056625,NaN,83.649948,30.761566,192.437729,389.920013,111.721512,35.297382,...,191.497086,18.444065,91.278015,57.260838,39.234821,66.298126,86.586670,121.772095,269.019989,136.834579

In [33]:
MINIMUM_DATA_POINTS = 100
valid_historical_prices = historical_prices.loc[:, historical_prices.count() >= MINIMUM_DATA_POINTS]
valid_historical_prices
# no_of_datapoints = historical_prices.count()
# valid_data_points = no_of_datapoints[no_of_datapoints >= MINIMUM_DATA_POINTS].index
# valid_data_points
# valid_historical_prices = historical_prices[valid_data_points]
# valid_historical_prices
# # historical_prices = historical_prices[valid_data_points]

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-05-08,77.063370,75.465767,68.410103,NaN,85.754929,24.675817,175.058151,367.510010,100.345612,31.711102,...,184.449936,16.551296,85.091537,51.682144,36.429157,59.362701,78.502274,113.823318,242.919998,120.456299
2020-05-11,78.571579,76.653259,71.620399,NaN,87.923981,24.019697,174.306198,371.420013,99.057388,30.874533,...,186.926758,16.134382,80.912323,51.527897,36.082054,58.919838,78.675362,110.208542,235.259995,121.339523
2020-05-12,77.198723,75.777245,73.706261,NaN,85.846436,22.488750,172.421539,365.100006,97.394554,30.273249,...,187.665070,15.175493,76.987587,50.379601,35.478947,55.659603,76.516502,106.098732,230.199997,119.054626
2020-05-13,77.498428,74.862305,72.410751,NaN,84.345520,21.147984,168.039490,358.559998,94.836342,29.488968,...,184.281738,14.216602,75.137764,49.754028,33.717873,54.849255,73.273651,103.744919,223.080002,118.113800
2020-05-14,78.929298,75.322197,73.282578,NaN,83.997719,21.728031,167.101837,355.390015,96.380409,29.767828,...,188.478241,14.491762,76.635231,49.873993,34.015400,55.546528,75.869736,104.706993,221.770004,120.993919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-30,107.599998,212.500000,195.100006,121.919998,130.750000,90.680000,299.149994,374.980011,194.919998,47.750000,...,307.799988,25.910000,80.309998,70.699997,105.629997,120.570000,150.440002,103.050003,250.320007,156.399994
2025-05-01,106.459999,213.320007,193.339996,124.010002,130.880005,89.669998,300.529999,374.630005,193.740005,47.580002,...,306.359985,25.820000,80.040001,70.400002,105.779999,120.750000,148.600006,101.820000,249.639999,155.649994
2025-05-02,108.629997,205.350006,198.470001,125.260002,132.820007,92.480003,305.329987,380.869995,198.589996,47.849998,...,312.070007,26.160000,82.489998,70.769997,106.209999,124.250000,149.139999,102.379997,255.949997,157.440002
2025-05-05,108.370003,198.889999,196.070007,124.889999,132.600006,92.580002,307.709991,381.059998,197.720001,47.500000,...,309.290009,25.830000,82.980003,70.889999,103.269997,122.330002,146.580002,90.480003,250.699997,158.059998
2025-05-06,105.239998,198.509995,187.149994,121.669998,133.059998,93.000000,303.799988,382.980011,195.600006,48.320000,...,307.549988,25.540001,83.519997,71.059998,104.709999,120.449997,148.279999,92.269997,250.850006,149.869995

In [ ]:
import sys
import os

path = os.path.abspath(os.path.join(os.getcwd(),'../'))

sys.path.append(path )

import YData

output = YData.get_s_n_p_historical_data()

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  501 of 501 completed

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-05-13,77.498444,74.862305,72.410744,NaN,84.345497,21.147984,168.039520,358.559998,94.836357,29.488968,...,184.281738,14.216602,75.137749,49.754032,33.717869,54.849270,73.273643,103.744942,223.080002,118.113777
2020-05-14,78.929298,75.322205,73.282570,NaN,83.997719,21.728031,167.101852,355.390015,96.380394,29.767830,...,188.478241,14.491759,76.635231,49.873993,34.015404,55.546532,75.869743,104.706985,221.770004,120.993904
2020-05-15,78.880951,74.876907,73.909973,NaN,82.267982,21.851648,170.713303,365.299988,93.009056,29.732969,...,187.375336,14.450072,76.047989,49.608341,33.774166,54.830414,77.336319,104.977859,217.800003,122.395576
2020-05-18,80.882225,76.641083,74.529198,NaN,82.615761,23.163889,178.948166,367.970001,98.984283,31.196955,...,191.356918,15.984297,79.737839,51.527901,36.460014,58.439281,79.030617,114.579887,235.800003,126.168541
2020-05-19,79.248329,76.198219,74.309204,NaN,80.739586,23.087816,176.478622,372.200012,97.147858,30.651186,...,189.721283,15.442316,80.285919,51.159409,35.334198,57.072994,79.121727,115.775497,240.550003,128.971863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-06,105.239998,198.509995,187.149994,121.669998,133.059998,93.000000,303.799988,382.980011,195.600006,48.320000,...,307.549988,25.540001,83.519997,71.059998,104.709999,120.449997,148.279999,92.269997,250.850006,149.869995
2025-05-07,107.519997,196.250000,188.089996,123.120003,133.949997,92.690002,306.089996,384.970001,199.860001,47.880001,...,306.019989,25.820000,84.120003,71.360001,104.610001,121.089996,149.479996,94.129997,257.279999,155.990005
2025-05-08,108.699997,197.490005,185.580002,126.389999,134.000000,94.559998,308.880005,383.989990,202.779999,47.700001,...,309.170013,25.940001,86.589996,70.169998,106.070000,123.309998,147.979996,95.110001,265.369995,161.690002
2025-05-09,106.930000,198.529999,184.600006,127.040001,133.240005,94.540001,307.899994,383.279999,207.509995,48.529999,...,309.070007,26.209999,87.930000,70.610001,107.309998,122.849998,147.130005,95.209999,266.709991,159.270004
2025-05-12,113.430000,208.330002,191.429993,132.419998,133.199997,93.495003,319.559998,393.850006,222.360001,49.290001,...,305.140015,26.770000,93.660004,68.769997,109.070000,125.930000,147.255005,97.980003,296.160004,161.800003

In [ ]:
output.head()